# Generated by Django 5.2.3 on 2025-07-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='customer',
        ),
    ]
